### ISSUE TITLE
Undefined variable error on this line that keeps getting hit when we use monkeylearn

### ISSUE THREAD

**Issue by aaron-web-dev** [monkeylearn/monkeylearn-php#3]
https://github.com/monkeylearn/monkeylearn-php/blob/4329ec9fb02e58be16845342282e470915f9e1c8/src/SleepRequests.php#L39

**Comment by sjwensley** [comment]
It looks like this variable is never defined in the script, so this is definitely a bug.

**Comment by rsteca** [comment]
As stated here: http://php.net/manual/en/reserved.variables.httpresponseheader.php $http_response_header is a variable automatically defined when you call file_get_contents. 

I think the problem is that file_get_contents is being called with @ which suppresses the real error message of the failed request.
